engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
  duplication:
    enabled: true
    exclude_paths:
      - test/**/*
    config:
      languages:
        - javascript
ratings:
   paths:
   - lib/**/*.js
   - test/*.js
   - test/helpers/*.js
