language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - /^greenkeeper.*$/
git:
  depth: 999
script:
  - npm run test
after_success:
  - if [ -n "${CODECOV_TOKEN:-}" ]; then npm run codecov; fi
  - npm run coverage
  - npm run semantic-release
